const { onRequest } = require('firebase-functions/v2/https');
const { onDocumentCreated } = require('firebase-functions/v2/firestore');
const { defineSecret } = require('firebase-functions/params');
const admin = require('firebase-admin');
const Razorpay = require('razorpay');
const crypto = require('crypto');
admin.initializeApp();
const db = admin.firestore();
const RAZORPAY_KEY_ID = defineSecret('RAZORPAY_KEY_ID');
const RAZORPAY_KEY_SECRET = defineSecret('RAZORPAY_KEY_SECRET');
const GOOGLE_MAPS_API_KEY = defineSecret('GOOGLE_MAPS_API_KEY');
const cors=(req,res)=>{const o=req.get('Origin');if(o==='https://bookmycar.github.io')res.set('Access-Control-Allow-Origin',o);res.set('Vary','Origin');res.set('Access-Control-Allow-Methods','POST, OPTIONS');res.set('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS'){res.status(204).send('');return true}return false};
async function notifyAdmins(title,body,data={}){const s=await db.collection('adminTokens').get(),tokens=s.docs.map(d=>d.data().token).filter(Boolean);if(!tokens.length)return;const r=await admin.messaging().sendEachForMulticast({tokens,notification:{title,body},data:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)])),webpush:{fcmOptions:{link:'https://bookmycar.github.io/Book-my-car/Admin.html'}}});const bad=[];r.responses.forEach((x,i)=>{if(!x.success&&['messaging/registration-token-not-registered','messaging/invalid-registration-token'].includes(x.error?.code))bad.push(tokens[i])});if(bad.length){const b=db.batch();s.docs.forEach(d=>{if(bad.includes(d.data().token))b.delete(d.ref)});await b.commit()}}
exports.notifyNewBooking=onDocumentCreated({document:'bookings/{bookingId}',region:'asia-south1'},async e=>{const b=e.data?.data();if(b)await notifyAdmins('🚗 New Booking',`${b.customerName||'Customer'} • ${b.pickup||''} → ${b.destination||''} • ₹${Math.round(Number(b.totalFare||0)).toLocaleString('en-IN')}`,{type:'booking',bookingId:e.params.bookingId})});
exports.notifyNewCar=onDocumentCreated({document:'cars/{carId}',region:'asia-south1'},async e=>{const c=e.data?.data();if(c)await notifyAdmins('🚘 New Car Added',`${c.carName||'New car'} • Owner: ${c.ownerName||'Owner'}`,{type:'car',carId:e.params.carId})});

// Google-backed route calculation. The API key stays server-side in Secret Manager.
exports.calculateRoute=onRequest({region:'asia-south1',secrets:[GOOGLE_MAPS_API_KEY]},async(req,res)=>{if(cors(req,res))return;if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const {origin,destination}=req.body||{};if(typeof origin!=='string'||typeof destination!=='string'||origin.trim().length<2||destination.trim().length<2||origin.length>200||destination.length>200)return res.status(400).json({error:'Valid pickup and destination are required'});const key=GOOGLE_MAPS_API_KEY.value();const g=async address=>{const u='https://maps.googleapis.com/maps/api/geocode/json?address='+encodeURIComponent(address+', India')+'&components=country:IN&region=in&language=en&key='+encodeURIComponent(key);const r=await fetch(u);if(!r.ok)throw Error('Google location service unavailable');const j=await r.json();if(j.status!=='OK'||!j.results?.length)throw Error('Google location नहीं मिली: '+address);const x=j.results[0];return{lat:x.geometry.location.lat,lng:x.geometry.location.lng,address:x.formatted_address}};const A=await g(origin),B=await g(destination);if(A.lat===B.lat&&A.lng===B.lng)throw Error('Pickup और Destination एक ही जगह है।');const rr=await fetch('https://routes.googleapis.com/directions/v2:computeRoutes',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':'routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline,routes.legs.distanceMeters'},body:JSON.stringify({origin:{location:{latLng:{latitude:A.lat,longitude:A.lng}}},destination:{location:{latLng:{latitude:B.lat,longitude:B.lng}}},travelMode:'DRIVE',routingPreference:'TRAFFIC_UNAWARE',computeAlternativeRoutes:false,routeModifiers:{avoidTolls:false,avoidHighways:false,avoidFerries:false},languageCode:'en-IN',units:'METRIC'})});if(!rr.ok){const t=await rr.text();console.error(t);throw Error('Google road route service unavailable')}const j=await rr.json();const r=j.routes?.[0];if(!r||typeof r.distanceMeters!=='number')throw Error('Google driving route नहीं मिली');return res.json({oneWayKm:Number((r.distanceMeters/1000).toFixed(2)),duration:r.duration||'',origin:A,destination:B,polyline:r.polyline?.encodedPolyline||''})}catch(e){console.error(e);return res.status(500).json({error:e.message||'Route calculation failed'})}});

exports.getBooking=onRequest({region:'asia-south1'},async(req,res)=>{if(cors(req,res))return;if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const{bookingId,mobile}=req.body||{};if(typeof bookingId!=='string'||!bookingId.trim()||!/^\d{10}$/.test(String(mobile||'')))return res.status(400).json({error:'Booking ID and 10 digit mobile are required'});const s=await db.collection('bookings').doc(bookingId.trim()).get();if(!s.exists)return res.status(404).json({error:'Booking not found'});const b=s.data();if(String(b.mobile)!==String(mobile))return res.status(403).json({error:'Booking ID and mobile do not match'});return res.json({bookingId:s.id,booking:{customerName:b.customerName||'',mobile:'******'+String(b.mobile).slice(-4),pickup:b.pickup||'',destination:b.destination||'',carName:b.carName||'',date:b.date||'',pickupTime:b.pickupTime||'',tripType:b.tripType||'',distanceKm:Number(b.distanceKm||0),paymentMethod:b.paymentMethod||'',paymentStatus:b.paymentStatus||'Pending',status:b.status||'Pending',totalFare:Number(b.totalFare||0)}})}catch(e){console.error(e);return res.status(500).json({error:'Unable to load booking'})}});
exports.createRazorpayOrder=onRequest({secrets:[RAZORPAY_KEY_ID,RAZORPAY_KEY_SECRET],region:'asia-south1'},async(req,res)=>{if(cors(req,res))return;if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const{bookingId}=req.body||{};if(!bookingId||typeof bookingId!=='string')return res.status(400).json({error:'bookingId required'});const ref=db.collection('bookings').doc(bookingId),s=await ref.get();if(!s.exists)return res.status(404).json({error:'Booking not found'});const b=s.data();if(b.status!=='Pending')return res.status(400).json({error:'Booking is not pending'});if(b.paymentStatus==='Verified')return res.status(400).json({error:'Payment already verified'});const amount=Math.round(Number(b.totalFare||0)*100);if(!Number.isInteger(amount)||amount<100||amount>100000000)return res.status(400).json({error:'Invalid payment amount'});const rz=new Razorpay({key_id:RAZORPAY_KEY_ID.value(),key_secret:RAZORPAY_KEY_SECRET.value()}),o=await rz.orders.create({amount,currency:'INR',receipt:bookingId.slice(0,40),notes:{bookingId}});await ref.update({razorpayOrderId:o.id,paymentStatus:'Order Created',paymentGateway:'Razorpay',paymentUpdatedAt:admin.firestore.FieldValue.serverTimestamp()});return res.json({keyId:RAZORPAY_KEY_ID.value(),orderId:o.id,amount:o.amount,currency:o.currency,bookingId})}catch(e){console.error(e);return res.status(500).json({error:'Unable to create payment order'})}});
exports.verifyRazorpayPayment=onRequest({secrets:[RAZORPAY_KEY_ID,RAZORPAY_KEY_SECRET],region:'asia-south1'},async(req,res)=>{if(cors(req,res))return;if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const{bookingId,razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body||{};if(!bookingId||!razorpay_order_id||!razorpay_payment_id||!razorpay_signature)return res.status(400).json({error:'Payment verification data incomplete'});const ref=db.collection('bookings').doc(bookingId),s=await ref.get();if(!s.exists)return res.status(404).json({error:'Booking not found'});if(s.data().razorpayOrderId!==razorpay_order_id)return res.status(400).json({error:'Order mismatch'});const expected=crypto.createHmac('sha256',RAZORPAY_KEY_SECRET.value()).update(razorpay_order_id+'|'+razorpay_payment_id).digest('hex');if(expected!==razorpay_signature)return res.status(400).json({error:'Invalid payment signature'});await ref.update({paymentStatus:'Verified',razorpayPaymentId:razorpay_payment_id,razorpaySignatureVerified:true,paymentVerifiedAt:admin.firestore.FieldValue.serverTimestamp(),paymentUpdatedAt:admin.firestore.FieldValue.serverTimestamp()});return res.json({verified:true,bookingId})}catch(e){console.error(e);return res.status(500).json({error:'Payment verification failed'})}});